# -*- coding: utf-8 -*-
"""Shopify Stocks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ya0Oz13iC_afWFoEGtH1lUJKJor4mHqM
"""

from google.colab import drive
drive.mount('/content/drive')

file_path="/content/drive/MyDrive/shopify stocks.csv"

import pandas as pd
df = pd.read_csv(file_path)
df.head()

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

df['date'] = pd.to_datetime(df['date'], utc=True)
df = df.sort_values('date')
df = df.dropna()
df.head()

df['date'] = pd.to_datetime(df['date'], utc=True)
df = df.sort_values('date')
df = df.dropna()
df.head()

import matplotlib.pyplot as plt
plt.figure(figsize=(12, 6))
plt.plot(df['date'], df['open'], label='Open')
plt.plot(df['date'], df['high'], label='High')
plt.plot(df['date'], df['low'], label='Low')
plt.plot(df['date'], df['close'], label='Close')
plt.title('Shopify OHLC Prices Over Time')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(12, 5))
plt.plot(df['date'], df['volume'])
plt.title('Shopify Trading Volume Over Time')
plt.xlabel('Date')
plt.ylabel('Volume')
plt.grid()
plt.show()

df['Daily_Return'] = df['close'].pct_change() * 100
df.head()

df['MA_20'] = df['close'].rolling(window=20).mean()

df['MA_50'] = df['close'].rolling(window=50).mean()

plt.figure(figsize=(14, 6))
plt.plot(df['date'], df['close'], label='Daily Close')
plt.plot(df['date'], df['MA_20'], label='20-Day MA')
plt.plot(df['date'], df['MA_50'], label='50-Day MA')
plt.title('Shopify Closing Price with Moving Averages')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(10, 5))
plt.hist(
    df['Daily_Return'].dropna(),
    bins=50
)
plt.title('Distribution of Shopify Daily Returns')
plt.xlabel('Daily Return (%)')
plt.ylabel('Frequency')
plt.grid()
plt.show()

import seaborn as sns
plt.figure(figsize=(10, 5))
sns.kdeplot(
    df['Daily_Return'].dropna(),
    fill=True
)
plt.title('KDE Plot of Shopify Daily Returns')
plt.xlabel('Daily Return (%)')
plt.ylabel('Density')
plt.grid()
plt.show()

plt.figure(figsize=(10, 5))
sns.histplot(
    df['Daily_Return'].dropna(),
    bins=50,
    kde=True
)
plt.title('Shopify Daily Returns - Histogram and KDE')
plt.xlabel('Daily Return (%)')
plt.ylabel('Frequency')
plt.grid()
plt.show()

volatility = df['Daily_Return'].std()
print("Daily Volatility:", volatility, "%")

mean_return = df['Daily_Return'].mean()
std_return = df['Daily_Return'].std()
high_volatility = df[
    abs(df['Daily_Return'] - mean_return) > 2 * std_return
]
print(high_volatility[
    ['date', 'close', 'Daily_Return']
])

highest_gain = df.loc[
    df['Daily_Return'].idxmax()
]
highest_loss = df.loc[
    df['Daily_Return'].idxmin()
]
print("Highest Gain:")
print(highest_gain[['date', 'Daily_Return']])
print("\nHighest Loss:")
print(highest_loss[['date', 'Daily_Return']])

print("===== SHOPIFY STOCK FINANCIAL SUMMARY ====")
print("Start Date:", df['date'].min())
print("End Date:", df['date'].max())
print("Starting Price:", df['close'].iloc[0])
print("Ending Price:", df['close'].iloc[-1])
print("Highest Price:", df['high'].max())
print("Lowest Price:", df['low'].min())
print("Average Closing Price:", df['close'].mean())
print("Average Daily Return:", df['Daily_Return'].mean(), "%")
print("Daily Volatility:", df['Daily_Return'].std(), "%")
print("Number of High-Volatility Days:", len(high_volatility))

