# -*- coding: utf-8 -*-
"""Sample Superstore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AcCfmWNH8e-nXI-hVcRDTe2NMxk4ZaAo
"""

from google.colab import drive
drive.mount('/content/drive')

file_path="/content/drive/MyDrive/samplesuperstore.csv"

# ==========================
# Sample Superstore Analysis
# Google Colab
# ==========================

# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt

# Upload CSV File
from google.colab import files
uploaded = files.upload()

# Read Dataset
df = pd.read_csv(next(iter(uploaded)))

# Display First 5 Rows
print("First 5 Rows")
display(df.head())

# Dataset Information
print("\nDataset Information")
df.info()

# Check Missing Values
print("\nMissing Values")
print(df.isnull().sum())

# Statistical Summary
print("\nStatistical Summary")
display(df.describe())

# Total Sales
total_sales = df["Sales"].sum()
print("Total Sales:", total_sales)

# Total Profit
total_profit = df["Profit"].sum()
print("Total Profit:", total_profit)

# ----------------------------
# Sales by Category
# ----------------------------
category_sales = df.groupby("Category")["Sales"].sum()

plt.figure(figsize=(8,5))
category_sales.plot(kind="bar")
plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Sales")
plt.xticks(rotation=0)
plt.show()

# ----------------------------
# Profit by Category
# ----------------------------
category_profit = df.groupby("Category")["Profit"].sum()

plt.figure(figsize=(8,5))
category_profit.plot(kind="bar", color="green")
plt.title("Profit by Category")
plt.xlabel("Category")
plt.ylabel("Profit")
plt.xticks(rotation=0)
plt.show()

# ----------------------------
# Top 10 Products by Sales
# ----------------------------
top_products = df.groupby("Product Name")["Sales"].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(12,6))
top_products.plot(kind="bar")
plt.title("Top 10 Products by Sales")
plt.xlabel("Product")
plt.ylabel("Sales")
plt.xticks(rotation=75)
plt.show()

# ----------------------------
# Sales by Region
# ----------------------------
region_sales = df.groupby("Region")["Sales"].sum()

plt.figure(figsize=(7,5))
region_sales.plot(kind="pie", autopct="%1.1f%%")
plt.title("Sales by Region")
plt.ylabel("")
plt.show()

# ----------------------------
# Profit vs Sales Scatter Plot
# ----------------------------
plt.figure(figsize=(8,6))
plt.scatter(df["Sales"], df["Profit"])
plt.title("Profit vs Sales")
plt.xlabel("Sales")
plt.ylabel("Profit")
plt.show()

# ----------------------------
# Top 10 Customers by Sales
# ----------------------------
top_customers = df.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,5))
top_customers.plot(kind="bar", color="orange")
plt.title("Top 10 Customers by Sales")
plt.xlabel("Customer")
plt.ylabel("Sales")
plt.xticks(rotation=75)
plt.show()

print("\nAnalysis Completed Successfully!")