# -*- coding: utf-8 -*-
"""Healthcare2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIfaYW7SuHWKsTzEIqpIuGGpBOEIBwDW
"""

from google.colab import drive
drive.mount('/content/drive')

file_path="/content/drive/MyDrive/healthcare_dataset.csv"

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(file_path)
df.head()

print(df.shape)

print(df.columns.tolist())

df['Date of Admission'] = pd.to_datetime(
    df['Date of Admission'],
    errors='coerce'
)

df['Discharge Date'] = pd.to_datetime(
    df['Discharge Date'],
    errors='coerce'
)

df['Stay_Days'] = (
    df['Discharge Date'] - df['Date of Admission']
).dt.days

display(df[['Date of Admission', 'Discharge Date', 'Stay_Days']].head())

billing_stack = pd.pivot_table(
    df,
    values='Billing Amount',
    index='Medical Condition',
    columns='Insurance Provider',
    aggfunc='sum',
    fill_value=0
)

billing_stack.plot(
    kind='bar',
    stacked=True,
    figsize=(12, 6)
)

plt.title('Billing Amount by Medical Condition and Insurance Provider')
plt.xlabel('Medical Condition')
plt.ylabel('Total Billing Amount')

plt.xticks(rotation=45)
plt.legend(title='Insurance Provider')
plt.grid(axis='y')

plt.show()

plt.figure(figsize=(12, 6))

sns.violinplot(
    data=df,
    x='Medical Condition',
    y='Billing Amount'
)

plt.title('Billing Amount by Medical Condition')
plt.xlabel('Medical Condition')
plt.ylabel('Billing Amount')

plt.xticks(rotation=45)

plt.grid(axis='y')

plt.show()

plt.figure(figsize=(12, 6))

sns.violinplot(
    data=df,
    x='Insurance Provider',
    y='Billing Amount'
)

plt.title('Billing Amount by Insurance Provider')
plt.xlabel('Insurance Provider')
plt.ylabel('Billing Amount')

plt.xticks(rotation=45)

plt.grid(axis='y')

plt.show()

df['Date of Admission'] = pd.to_datetime(
    df['Date of Admission'],
    errors='coerce'
)

print(df['Date of Admission'].head())

monthly_admissions = (
    df.groupby(
        df['Date of Admission'].dt.to_period('M')
    )
    .size()
)

print(monthly_admissions)

peak_month = monthly_admissions.idxmax()

peak_admissions = monthly_admissions.max()

print("Peak Admission Month:", peak_month)
print("Number of Admissions:", peak_admissions)

correlation_data = df[
    ['Age', 'Stay_Days', 'Billing Amount']
]

correlation_matrix = correlation_data.corr()

print(correlation_matrix)

plt.figure(figsize=(8, 6))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title(
    'Correlation Matrix: Age, Stay Duration and Medical Cost'
)

plt.show()

avg_billing_condition = df.groupby(
    'Medical Condition'
)['Billing Amount'].mean()

print(avg_billing_condition)

avg_billing_insurance = df.groupby(
    'Insurance Provider'
)['Billing Amount'].mean()

print(avg_billing_insurance)

print("========== HEALTHCARE EXECUTIVE SUMMARY ==========")

print("\nTotal Patients:", len(df))

print(
    "Average Billing Amount:",
    round(df['Billing Amount'].mean(), 2)
)

print(
    "Average Hospital Stay:",
    round(df['Stay_Days'].mean(), 2),
    "days"
)

print(
    "Average Patient Age:",
    round(df['Age'].mean(), 2)
)

print(
    "\nMost Common Medical Condition:",
    df['Medical Condition'].mode()[0]
)

print(
    "Most Common Insurance Provider:",
    df['Insurance Provider'].mode()[0]
)

print(
    "\nPeak Admission Month:",
    peak_month
)

print(
    "Peak Admissions:",
    peak_admissions
)

print("Final Dataset:")

display(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nMissing Values:")
print(df.isnull().sum())